# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyh9WvsymBe2OpZ0VetlR1Z8rcfmNkG6
"""

!pip install experta

!sed -i 's/collections.Mapping/collections.abc.Mapping/' /usr/local/lib/python3.10/dist-packages/frozendict/__init__.py

import collections
import collections.abc
collections.Mapping = collections.abc.Mapping
from experta import * # هنا اتسيراد المكتبة
# facts تعريف
class Environment(Fact): # بيئة العمل
    """Represents the environment a trainee interacts with."""
    pass

class Job(Fact): # نوع الوظيفة
    """Represents the job type for the trainee."""
    pass

class Feedback(Fact): # هل يوجد فيدباك ام لا
    """Indicates whether feedback is required."""
    pass

class Medium(Fact): # وسيلة التدريب المناسبة medium
    """Represents the medium selected based on rules."""
    pass

class MediaAdvisor(KnowledgeEngine):  #  العقل زي ما بحكو
    def __init__(self):
        super().__init__()
        print("Initializing the Media Advisor Expert System...\n")
# Rule 1
#  اذا كان البيئة : اوراق او كتيبات او مستندات او كتب  اذا هي  verbal
    @Rule(Environment(environment='papers') |
          Environment(environment='manuals') |
          Environment(environment='documents') |
          Environment(environment='textbooks'))
    def verbal(self):
        print("Rule triggered: Environment is 'verbal'.")
        self.declare(Fact(stimulus_situation='verbal'))

# Rule 2
#اذا كانت البيئة صور او رسومات او مخططات اذا هي visual
    @Rule(Environment(environment='pictures') |
          Environment(environment='illustrations') |
          Environment(environment='photographs') |
          Environment(environment='diagrams'))
    def visual(self):
        print("Rule triggered: Environment is 'visual'.")
        self.declare(Fact(stimulus_situation='visual'))
# Rule 3
#اذا كانت البيئة الات او ادوات او مباني  اذا هي physical object
    @Rule(Environment(environment='machines') |
          Environment(environment='buildings') |
          Environment(environment='tools'))
    def physical_object(self):
        print("Rule triggered: Environment is a 'physical object'.")
        self.declare(Fact(stimulus_situation='physical object'))
# Rule 4
#اذا كانت البيئة الارقام او معادلات او برامج  اذا هي symbolic
    @Rule(Environment(environment='numbers') |
          Environment(environment='formulas') |
          Environment(environment='computer programs'))
    def symbolic(self):
        print("Rule triggered: Environment is 'symbolic'.")
        self.declare(Fact(stimulus_situation='symbolic'))
# Rule 5
    @Rule(Job(job='lecturing') |
          Job(job='advising') |
          Job(job='counselling'))
    def oral_response(self):
        print("Rule triggered: Job requires 'oral' response.")
        self.declare(Fact(stimulus_response='oral'))
# Rule 6
    @Rule(Job(job='building') |
          Job(job='repairing') |
          Job(job='troubleshooting'))
    def hands_on(self):
        print("Rule triggered: Job requires 'hands-on' response.")
        self.declare(Fact(stimulus_response='hands-on'))
# Rule 7
    @Rule(Job(job='writing') |
          Job(job='typing') |
          Job(job='drawing'))
    def documented_response(self):
        print("Rule triggered: Job requires 'documented' response.")
        self.declare(Fact(stimulus_response='documented'))
# Rule 8
    @Rule(Job(job='evaluating') |
          Job(job='reasoning') |
          Job(job='investigating'))
    def analytical_response(self):
        print("Rule triggered: Job requires 'analytical' response.")
        self.declare(Fact(stimulus_response='analytical'))
# Rule 9
    @Rule(Fact(stimulus_situation='physical object'),
          Fact(stimulus_response='hands-on'),
          Feedback(feedback='required'))
    def workshop(self):
        print("Final Rule triggered: Selecting medium 'Workshop'.")
        self.declare(Medium(medium='workshop'))
        print("Recommended Medium: Workshop\n")
# Rule 10
    @Rule(Fact(stimulus_situation='symbolic'),
          Fact(stimulus_response='analytical'),
          Feedback(feedback='required'))
    def lecture_tutorial_symbolic(self):
        print("Final Rule triggered: Selecting medium 'Lecture - Tutorial' for symbolic environment.")
        self.declare(Medium(medium='lecture - tutorial'))
        print("Recommended Medium: Lecture - Tutorial\n")
# Rule 11 - Modified for conflict resolution: Removed feedback condition and added salience=10.
# This rule now gives higher priority (salience=10) to videocassette for visual and documented responses, regardless of feedback.
    @Rule(Fact(stimulus_situation='visual'),
          Fact(stimulus_response='documented'),
          salience=10)
    def videocassette(self):
        print("Final Rule triggered: Selecting medium 'Videocassette'.")
        self.declare(Medium(medium='videocassette'))
        print("Recommended Medium: Videocassette\n")
# Rule 12
    @Rule(Fact(stimulus_situation='verbal'),
          Fact(stimulus_response='analytical'),
          Feedback(feedback='required'))
    def lecture_tutorial_verbal(self):
        print("Final Rule triggered: Selecting medium 'Lecture - Tutorial' for verbal environment.")
        self.declare(Medium(medium='lecture - tutorial'))
        print("Recommended Medium: Lecture - Tutorial\n")


    @Rule(Fact(stimulus_situation='visual'),
          Fact(stimulus_response='documented'),
          Feedback(feedback='required'),
          salience=5)
    def online_course(self):
        print("Final Rule triggered: Selecting medium 'Online Course'.")
        self.declare(Medium(medium='online course'))
        print("Recommended Medium: Online Course\n")

advisor = MediaAdvisor()

# Test Case 1: Workshop (Physical object, Hands-on, Feedback required)
print("Test Case 1:")
advisor.reset()
advisor.declare(Environment(environment='machines'))
advisor.declare(Job(job='repairing'))
advisor.declare(Feedback(feedback='required'))
advisor.run()

# Test Case 2: Videocassette (Visual, Documented, No Feedback)
print("Test Case 2:")
advisor.reset()
advisor.declare(Environment(environment='pictures'))
advisor.declare(Job(job='writing'))
advisor.declare(Feedback(feedback='not required'))
advisor.run()

# Test Case 3: Lecture-Tutorial for Symbolic Environment (Symbolic, Analytical, Feedback required)
print("Test Case 3:")
advisor.reset()
advisor.declare(Environment(environment='formulas'))
advisor.declare(Job(job='reasoning'))
advisor.declare(Feedback(feedback='required'))
advisor.run()

# Test Case 4: Lecture-Tutorial for Verbal Environment (Verbal, Analytical, Feedback required)
print("Test Case 4:")
advisor.reset()
advisor.declare(Environment(environment='manuals'))
advisor.declare(Job(job='investigating'))
advisor.declare(Feedback(feedback='required'))
advisor.run()

# Test Case 5: No Matching Rule (Visual, Oral, Feedback required)
print("Test Case 5:")
advisor.reset()
advisor.declare(Environment(environment='diagrams'))
advisor.declare(Job(job='advising'))
advisor.declare(Feedback(feedback='required'))
advisor.run()

# Test Case 6: No Feedback Scenario (Symbolic, Analytical, No Feedback)
print("Test Case 6:")
advisor.reset()
advisor.declare(Environment(environment='computer programs'))
advisor.declare(Job(job='evaluating'))
advisor.declare(Feedback(feedback='not required'))
advisor.run()

# Test the conflict scenario
print("Test Case: Conflict Scenario (Visual + Documented + Feedback Required)")
advisor.reset()
advisor.declare(Environment(environment='pictures'))
advisor.declare(Job(job='writing'))
advisor.declare(Feedback(feedback='required'))
advisor.run()